name: molsub_test
channels:
  - defaults
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - albucore=0.0.16
  - albumentations=1.4.15
  - annotated-types=0.7.0
  - aom=3.6.0
  - blas=1.1
  - blosc=1.21.3
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.32.3
  - ca-certificates=2024.9.24
  - cairo=1.16.0
  - cfitsio=3.470
  - charls=2.2.0
  - dav1d=1.2.1
  - dbus=1.13.18
  - eigen=3.4.0
  - eval-type-backport=0.2.0
  - eval_type_backport=0.2.0
  - expat=2.6.3
  - ffmpeg=4.2.3
  - fontconfig=2.14.1
  - freetype=2.10.4
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - icu=73.1
  - imagecodecs=2023.1.23
  - imageio=2.36.0
  - importlib-metadata=8.5.0
  - jpeg=9e
  - jxrlib=1.1
  - krb5=1.20.1
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20240116.2
  - libaec=1.0.6
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.9.1
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.3
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libopenblas=0.3.28
  - libpng=1.6.39
  - libpq=12.17
  - libprotobuf=4.25.3
  - libssh2=1.10.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxkbcommon=1.0.3
  - libxml2=2.13.1
  - libzopfli=1.0.3
  - lz4-c=1.9.4
  - mysql=5.7.20
  - ncurses=6.4
  - nettle=3.6
  - networkx=3.4.2
  - numexpr=2.10.1
  - openblas=0.3.28
  - opencv=4.10.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.3.2
  - packaging=24.1
  - pcre2=10.42
  - pixman=0.40.0
  - pthread-stubs=0.4
  - pydantic=2.9.2
  - pydantic-core=2.23.4
  - python=3.10.15
  - python-tzdata=2023.3
  - python_abi=3.10
  - pywavelets=1.7.0
  - pyyaml=6.0.2
  - qt-main=5.15.2
  - readline=8.2
  - scikit-image=0.24.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.45.3
  - tk=8.6.14
  - tomli=2.0.2
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - wheel=0.44.0
  - x264=1!152.20180806
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xz=5.4.6
  - yaml=0.2.5
  - zfp=1.0.1
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - accelerate==1.2.1
      - adabelief-pytorch==0.2.1
      - addict==2.4.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.9
      - aiosignal==1.3.1
      - async-timeout==5.0.1
      - attrs==24.2.0
      - basicsr==1.4.2
      - betacal==1.1.0
      - box==0.1.5
      - calflops==0.3.2
      - causal-conv1d==1.5.0.post8
      - certifi==2024.8.30
      - chardet==5.2.0
      - charset-normalizer==3.4.0
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - columnar==1.3.1
      - contourpy==1.3.0
      - cvxopt==1.3.2
      - cycler==0.12.1
      - diffusers==0.31.0
      - docopt==0.6.2
      - einops==0.8.0
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - executing==0.8.2
      - facexlib==0.3.0
      - faster-coco-eval==1.6.5
      - filelock==3.16.1
      - filterpy==1.4.5
      - fonttools==4.54.1
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - ftfy==6.3.1
      - future==1.0.0
      - gfpgan==1.3.8
      - grad-cam==1.5.5
      - grpcio==1.68.1
      - h5py==3.12.1
      - huggingface-hub==0.27.0
      - idna==3.10
      - imbalanced-learn==0.12.4
      - imblearn==0.0
      - importlib-resources==6.4.5
      - iniconfig==2.0.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - kornia==0.7.3
      - kornia-rs==0.1.7
      - lightning-utilities==0.11.9
      - llvmlite==0.43.0
      - lmdb==1.5.1
      - loguru==0.7.2
      - markdown==3.7
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - medpy==0.5.2
      - ml-collections==1.0.0
      - ml-insights==1.0.4
      - mlinsights==0.5.1
      - mpmath==1.3.0
      - multidict==6.1.0
      - narwhals==1.26.0
      - nibabel==5.3.2
      - ninja==1.11.1.3
      - numba==0.60.0
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - onnx==1.17.0
      - open-clip-torch==2.30.0
      - openpyxl==3.1.5
      - pandas==2.2.3
      - pillow==11.0.0
      - pip==25.0.1
      - platformdirs==4.3.6
      - plotly==6.0.0
      - pluggy==1.5.0
      - propcache==0.2.1
      - protobuf==5.28.3
      - psutil==6.1.0
      - py-cpuinfo==9.0.0
      - pyaml==24.9.0
      - pycocotools==2.0.8
      - pydicom==3.0.1
      - pykwalify==1.8.0
      - pyparsing==3.2.0
      - pyradiomics==3.0.1
      - pysqlite3-binary==0.5.4
      - pytest==8.3.4
      - python-dateutil==2.8.2
      - pytorch-lightning==2.5.0.post0
      - pytz==2024.2
      - realesrgan==0.3.0
      - regex==2024.11.6
      - requests==2.32.3
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.12
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scikit-optimize==0.10.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - setuptools==75.3.0
      - simpleitk==2.4.0
      - splinecalib==0.0.9
      - submitit==1.5.2
      - sympy==1.13.1
      - tabulate==0.9.0
      - tb-nightly==2.19.0a20241216
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.5.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - timeago==1.0.14
      - timm==1.0.12
      - tokenizers==0.21.0
      - toolz==1.0.0
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchmetrics==1.6.1
      - torchvision==0.20.1
      - tqdm==4.66.6
      - transformers==4.47.0
      - triton==3.1.0
      - ttach==0.0.3
      - tzdata==2024.2
      - ultralytics==8.3.78
      - ultralytics-thop==2.0.14
      - urllib3==2.2.3
      - vit-pytorch==1.8.7
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - xlrd==2.0.1
      - xlwt==1.3.0
      - yacs==0.1.8
      - yapf==0.43.0
      - yarl==1.18.3
